language: rust
cache: cargo

os:
  - linux
  - osx
  - windows

dist: xenial

rust:
  - stable
  - nightly

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install libfuse-dev; fi

addons:
 apt:
   packages:
     - attr
     - e2fsprogs

script:
  - cargo build --verbose
  - cargo test --verbose --package rrg-macro --package rrg-proto --package rrg --features 'test-chattr test-setfattr'
  - cargo run -- --version
